### ISSUE TITLE
[Bug report] FileItem返回JSON字段变了

### ISSUE THREAD

**Issue by szuwest** [fluttercandies/baidupan#10]
### Version

1.2.1

### Platforms

dart

### Device Model

Android 8.0

### flutter info

```sh
Flutter (Channel stable, 3.13.2, on macOS 13.1 22C65 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.13.2 on channel stable at
      /Users/kk/Documents/software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (3 months ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

### How to reproduce?

获取文件列表list
{"errno":0,"guid_info":"","list":[{"path":"\/test\/LDN-AL10(20231128)","share":0,"fs_id":0,"dir_empty":0}],"request_id":8886478411554518438,"guid":0}

tkbindId等很多字段都没了。
JSON解析的报错 
Unhandled Exception: type 'Null' is not a subtype of type 'int'

主要是因为你model里的字段都是 
严格不能为空的字段定义 final int tkbindId;
如果改为 final int? tkbindId; 就应该没事

**Comment by szuwest** [comment]
参数问题，不能传folder=1

**Comment by CaiJingLong** [comment]
所以，是库有问题还是啥，issue 如果没解决，可以重新 open，虽然我不一定有时间修就是了
另外也欢迎PR
