### ISSUE TITLE
[Discussions]没有专门的创建文件夹/文件的接口吗？必须用precreate? 

### ISSUE THREAD

**Issue by szuwest** [fluttercandies/baidupan#7]
### Content

找了一下，貌似没找到专门的创建文件夹的接口。
我仅仅是想创建一个文件夹而已，不需要用到precreate吧

**Comment by CaiJingLong** [comment]
对接的时候比较早，当时还没有单独创建文件夹的接口
倒是可以加一个

**Comment by CaiJingLong** [comment]
1.2.0

**Comment by szuwest** [comment]
太厉害了，这么快就加上了。。。感谢做了这么好的一个库
